apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdig-agent
data:
  dragent.yaml: |
    ### Agent tags
    # tags: linux:ubuntu,dept:dev,local:nyc
 
    #### Sysdig Software related config ####
 
    # Sysdig collector address
    collector: collector-static.sysdigcloud.com
 
    # Collector TCP port
    collector_port: 6443
 
    # Whether collector accepts ssl/TLS
    ssl: true
 
    # collector certificate validation
    ssl_verify_certificate: true
 
    # Sysdig Secure
    security:
        enabled: true
 
    #######################################
    # new_k8s: true
    # k8s_cluster_name: production
